### ISSUE TITLE
Per server configurations

### ISSUE THREAD

**Issue by unzarii** [unzarii/Momiji-Bot#4]
Just prefix for now.

**Comment by momijisama** [comment]
Will require database crap
Not sure whether to use the funny things the guides keep suggesting or an actual SQL database

**Comment by momijisama** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issues as of this current moment in time](https://trello.com/c/efOCOBkA/1-issues-as-of-this-current-moment-in-time)
